spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tododb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: # 구글 이메일
    password: # 2차 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "0da56a0700a56821782b91c49ce03b42"
            redirect-uri: "https://ssafysandbox.vercel.app/oauth/redirect"
            authorization-grant-type: authorization_code


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


